server:
  port: 8083

spring:
  application:
    name: glu-problem
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # ----- Config Server에서 처리 -----
  # Cloud
  cloud:
    config:
      enabled: false

  data:
    mongodb:
      uri: mongodb+srv://S11P22A506:denr23bdoE@ssafy.ngivl.mongodb.net/S11P22A506?authSource=admin

#  # JPA
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: create