name: glu

services:
  glu-eureka:
    container_name: glu-eureka
    image: ssafyglu/glu-eureka:latest
    networks:
      - glu-network
    ports:
      - '${EUREKA_PORT}:${EUREKA_PORT}'
  glu-config:
    container_name: glu-config
    image: ssafyglu/glu-config:latest
    networks:
      - glu-network
    ports:
      - '${CONFIG_PORT}:${CONFIG_PORT}'
  glu-gateway:
    container_name: glu-gateway
    image: ssafyglu/glu-gateway:latest
    networks:
      - glu-network
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
  glu-problem:
    container_name: glu-problem
    image: ssafyglu/glu-problem:latest
    networks:
      - glu-network
    ports:
      - '${PROBLEM_PORT}:${PROBLEM_PORT}'

networks:
  glu-network:
    driver: bridge
