server:
  port: 8082

spring:
  application:
    name: glu-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # ----- Config Server에서 처리 -----
  # Cloud
  cloud:
    config:
      enabled: false

  # MySQL
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/glu
    username: root
    password: ssafy

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create