server:
  port: 8080
  auth:
    granted: "Bearer"
  header:
    user-id: "X-User-Id"

spring:
  application:
    name: glu-gateway
  cloud:
    gateway:
      routes:
        # 공통 코드 서버
        - id: common-router
          uri: lb://GLU-COMMON
          predicates:
            - Path=/api/common/**
        # 공통 코드 서버 swagger
        - id: common-swagger
          uri: lb://GLU-COMMON
          predicates:
            - Path=/docs/glu-common/**
          filters:
            - RewritePath=/docs/glu-common/(?<path>.*), /$\{path}
        # 문제 서버
        - id: problem-router
          uri: lb://GLU-PROBLEM
          predicates:
            - Path=/api/problems/**
          filters:
            - name: PreGatewayAuthorizationFilterFactory
        # 문제 서버 swagger
        - id: problem-swagger
          uri: lb://GLU-PROBLEM
          predicates:
            - Path=/docs/glu-problem/**
          filters:
            - RewritePath=/docs/glu-problem/(?<path>.*), /$\{path}
        # 유저 서버
        - id: user-router
          uri: lb://GLU-USER
          predicates:
            - Path=/api/users/**
          filters:
            - name: PreGatewayAuthorizationFilterFactory
        # 유저 서버 swagger
        - id: user-swagger
          uri: lb://GLU-USER
          predicates:
            - Path=/docs/glu-user/**
          filters:
            - RewritePath=/docs/glu-user/(?<path>.*), /$\{path}
        # 인증 서버
        - id: auth-router
          uri: lb://GLU-AUTH
          predicates:
            - Path=/api/auth/**
        # 인증 서버 swagger
        - id: auth-swagger
          uri: lb://GLU-AUTH
          predicates:
            - Path=/docs/glu-auth/**
          filters:
            - RewritePath=/docs/glu-auth/(?<path>.*), /$\{path}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    use-root-path: true
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /docs/glu-common/v3/api-docs
        name: glu-common
      - url: /docs/glu-problem/v3/api-docs
        name: glu-problem
      - url: /docs/glu-user/v3/api-docs
        name: glu-user
      - url: /docs/glu-auth/v3/api-docs
        name: glu-auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://glu-eureka:8761/eureka}

jwt:
  claims-name:
    user-id: "userId"
  secret: "secretarysecretarysecretarysecretarysecretarysecretary"
