spring:
  application:
    name: glu-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${CONFIG_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, refresh