server:
    port: 9000

spring:
    application:
        name: glu-config
    cloud:
        config:
            server:
                git:
                    uri: ${GIT_URI}
                    ignore-local-ssh-settings: true
                    private-key: ${PRIVATE_KEY}
                    host-key: ${HOST_KEY}
                    host-key-algorithm: ${HOST_KEY_ALGORITHM}
    security:
        user:
            name: ${SPRING_SECURITY_USER_NAME}
            password: ${SPRING_SECURITY_USER_NAME}

# actuator 설정
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true