server:
    port: 9000

spring:
    application:
        name: glu-config
    cloud:
        config:
            server:
                git:
                    uri: git@github.com:E-Glu/glu-config.git
                    ignore-local-ssh-settings: true
                    private-key: |
                        -----BEGIN EC PRIVATE KEY-----
                        MHcCAQEEIHIXr9Y0RwNkEyE3h3C7yqPExyZr2iHUlttQO1k3XWFvoAoGCCqGSM49
                        AwEHoUQDQgAEKeiqn/IbIduDVjijyUz5MS/emMOqxigcRcTe5zt971LvEsEZLJih
                        pdv4gX+U8wjniv77FCHYMnqfe+FwzD2vNA==
                        -----END EC PRIVATE KEY-----
                    host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
                    host-key-algorithm: ecdsa-sha2-nistp256
# actuator 설정
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true